### ISSUE TITLE
Publish new version (0.3?) now that #3 is merged

### ISSUE THREAD

**Issue by NorthIsUp** [databricks/intellij-jsonnet#10]
now that #3 is landed can we get a new release please? this should also close out #8.

**Comment by lihaoyi-databricks** [comment]
Uploaded a new 0.3 build to https://plugins.jetbrains.com/plugin/10852-jsonnet built off of 4b2711cea38dc3187548c1bee949dfc9a34342fa. Hopefully should appear soon, feel free to make noise if it doesn't
