### ISSUE TITLE
Highlight matching braces

### ISSUE THREAD

**Issue by millern** [databricks/intellij-jsonnet#21]
Thanks for the work on this. Is it possible to make IntelliJ highlight matching braces, parentheses, & brackets in jsonnet files with this plugin?

**Comment by lihaoyi-databricks** [comment]
Implemented in https://github.com/databricks/intellij-jsonnet/commit/eed3186adc6a90b50beede01f6d5a65b97b28da2, which should go out in version 1.1 once it goes through jetbrains' publishing process
