### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by evenh** [databricks/intellij-jsonnet#29]
Hi Databricks folks!

First of all, thanks for a wonderful plugin - I use it almost every day.

I'm wondering if this project still is maintained? There haven't been any commits for over a year (Mar 2020) + there is only one PR open which is about the same age.

I see that a similar jsonnet-project, [sjsonnet](https://github.com/databricks/sjsonnet) is getting some attention, so there is at least an indication that Databricks is using jsonnet internally.

cc @lihaoyi-databricks

**Comment by lihaoyi-databricks** [comment]
Yes, our whole org uses the plugin daily. What works, works. Feel free to send PRs for additional functionality or improvements!
