### ISSUE TITLE
Jump to identifier reference does not respect select.

### ISSUE THREAD

**Issue by andrewmchen** [databricks/intellij-jsonnet#6]
Minimal reproducible case.

```
local a = 1;
{
  a: a,
  b: $.a,
}
```

**Comment by lihaoyi** [comment]
yeah we should probably just ignore the `bar` in `foo.bar` style selects for now until we can do something clever about looking up what members `foo` has

**Comment by lihaoyi-databricks** [comment]
Should be addressed by `https://github.com/databricks/intellij-jsonnet/pull/16` I think
