### ISSUE TITLE
Support for other JetBrains IDEs

### ISSUE THREAD

**Issue by jessechahal** [databricks/intellij-jsonnet#8]
I have tested the latest release of 0.2 using the latest pycharm 2018.2 IDE. I did this by downloading the release from https://plugins.jetbrains.com/plugin/10852-jsonnet and installing it manually. No code highlighting or such was activated. I saw that https://github.com/databricks/intellij-jsonnet/commit/4b2711cea38dc3187548c1bee949dfc9a34342fa seems to attempt to add support for all JetBrains IDE's. 

It would be nice if support for for other JetBrains IDEs were added. IDE languages where i think this would be most useful would be Python, Ruby, golang. Jsonnet is used in ksonnet which is commonly used for building kubernetes clusters. Developers who are writing code for operations are most likely using either Python or Ruby, newer projects might be in golang.

**Comment by lihaoyi-databricks** [comment]
Uploaded a new 0.3 build to https://plugins.jetbrains.com/plugin/10852-jsonnet built off of 4b2711cea38dc3187548c1bee949dfc9a34342fa. Hopefully should appear soon, feel free to make noise if it doesn't
